### ISSUE TITLE
File system API

### ISSUE THREAD

**Issue by 0neGuyDev** [Matchstic/libwidgetinfo#37]
[Tweet regarding the idea of this API](https://twitter.com/0neGuyDev/status/1307377921821155334)

**Comment by Matchstic** [comment]
Please can you put the important parts of that tweet thread here. It makes things a little easier this end, especially in the (highly unlikely but possible) event the tweets are deleted.

**Comment by 0neGuyDev** [comment]
- Read contents of folders
- - See metadata for the contents, file type, data edited, etc etc
- Read files
- Delete files
- Move files
- Make files (Would then also support overwriting files)

And some API on XenHTML's end to limit where a widget can do things... I.e a widget has to have said in its `.plist` file what folders it needs access to and then it becomes a toggle in the widgets settings to allow it to use the API in the specified locations or not.

**Comment by Matchstic** [comment]
For the sake of easiness, I’m thinking that this API should be restricted to anything inside /var/mobile. This means that the security toggles won’t be needed, and allows implementation to be much simpler.

API itself would be promise based (no way around that), and would basically just wrap the appropriate NSFileManager functions.

Thoughts?

**Comment by 0neGuyDev** [comment]
Not a bad idea perhaps, a widget should just list off which folders it'll be touching and then it'll be allowed to do so in those folder only?

I'm mostly thinking of the end user here, people may get skeptical over the safety but if they know that it can't touch anything outside of what it says that might be a relief.

Maybe not that just my thoughts...

**Comment by Matchstic** [comment]
@0neGuyDev please have a look at the current implementation of the JS side here: https://github.com/Matchstic/libwidgetinfo/blob/367847a8ded4ffdc4717b3a68d2894218b558cb6/lib/Middleware/src/data/filesystem.ts

Its all promise based, and hopefully covers all the bases.

**Comment by Matchstic** [comment]
API is implemented and available to the public
